name: CI

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest

    env:
      CLOUDANT_AUTH_TYPE: "BASIC"
      CLOUDANT_URL: ${{ secrets.CLOUDANT_URL }}
      CLOUDANT_SYNC_DB: ${{ secrets.CLOUDANT_SYNC_DB}}
      CLOUDANT_USERNAME: ${{ secrets.CLOUDANT_USERNAME }}
      CLOUDANT_PASSWORD: ${{ secrets.CLOUDANT_PASSWORD }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      FULL_ACCESS_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            download-buffer-size = 134217728
            http-connections = 25
            max-substitution-jobs = 8

      - uses: cachix/cachix-action@v15
        with:
          name: devenv

      - name: Install devenv and run tests
        run: |
          nix profile install nixpkgs#devenv
          devenv shell test
        timeout-minutes: 10
