name: CI

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest

    env:
      CLOUDANT_AUTH_TYPE: "BASIC"
      CLOUDANT_URL: ${{ secrets.CLOUDANT_URL }}
      CLOUDANT_SYNC_DB: ${{ secrets.CLOUDANT_SYNC_DB}}
      CLOUDANT_USERNAME: ${{ secrets.CLOUDANT_USERNAME }}
      CLOUDANT_PASSWORD: ${{ secrets.CLOUDANT_PASSWORD }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      FULL_ACCESS_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache  
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install and run with devenv
        run: |
          nix profile install nixpkgs#devenv
          devenv shell test
        timeout-minutes: 10
