name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install devenv and check code
        run: |
          nix profile install nixpkgs#devenv
          devenv shell format-check
          devenv shell lint
        timeout-minutes: 10
