name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    container: nixos/nix:latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Check formatting
        run: devenv shell format-check
        timeout-minutes: 5

      - name: Run linting
        run: devenv shell lint
        timeout-minutes: 5
