name: Lint

on: push

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ruff-format
            run: ruff format --check .
          - name: ruff-check
            run: ruff check .
          - name: mypy
            run: mypy
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - run: uv sync --locked
      - run: uv run ${{ matrix.run }}
